# Usamos uma imagem oficial do Tomcat com Java 17 (ou 11 se preferir)
FROM tomcat:9.0-jdk17-openjdk-slim

# Removemos os apps padrão do Tomcat para limpar o caminho
RUN rm -rf /usr/local/tomcat/webapps/*

# Copiamos o conteúdo da sua pasta WebContent para dentro do Tomcat
# Nota: Se no seu Eclipse a pasta se chamar 'webapp', mude o nome abaixo
COPY webapp/ /usr/local/tomcat/webapps/ROOT/

# Expomos a porta 8080 que é o padrão do Tomcat e do Railway
EXPOSE 8080

CMD ["catalina.sh", "run"]